### ISSUE TITLE
#25

### ISSUE THREAD

**Issue by touwys** [htrinter/Open-Multiple-URLs#44] opened 2021-11-04 08:34 UTC
Please, reconsider implementing this proposed feature #25 by showing the number of tabs that's been added to the window. It will give the user a visual advance warning if the browser is about to be overloaded with tabs.

Thank you.

**Comment by jtagcat** [comment] 2021-11-04 21:00
Duplicate of #25, please don't file invalid issues.

**Comment by touwys** [comment] 2022-01-06 13:44
How then, should I reopen issue #25 when is has been closed?

**Closed as completed** 2022-01-06 17:09 UTC
Labels: duplicate
